### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by resom78** [gjf/gjf_bt#2]
I have installed the module through Magisk manager but it doesn't change anything to the bluetooth codec: In developper option I can't select dual channel and I don't hear any difference even if I choose 800kbit/s.
How to be sure the patch is applyied?

Anyway thanks for effort!

**Comment by gjf** [comment]
1. What ROM are you using?
2. If you installed the module from repository - you should ask in a proper repository: https://github.com/Magisk-Modules-Repo/gjf_bt/issues

**Comment by resom78** [comment]
I use stock ROM from my Unihertz Jelly Pro, and yes I installed the module from Magisk!
I open a new issue in the repo you mention
