### ISSUE TITLE
Cant install Redmi5Plus 

### ISSUE THREAD

**Issue by ghiki** [gjf/gjf_bt#3]
It happens in latest Apr. update, before this, instalación works.
Cant select anything with volumen Keys, ser screenshot (the text repeats and cant select anything)
![Screenshot_2019-06-27-03-16-02-266_com R ArO gTU5mji8Np](https://user-images.githubusercontent.com/854302/60226249-a739c280-988a-11e9-87e9-69b469a94f8e.png)

**Comment by JustACatRu** [comment]
Have the same issue on Xiaomi Mi Mix (android 7.0, miui 9.5.1.0).
But I'm able to install it 50/50. I mean, sometimes it works, and sometimes just starting to go crazy like on **ghiki** screenshot, then I have to kill Magisk Manager and repeat installation.

**Comment by ghiki** [comment]
But with this, It cant be installed. Older versión works fine

**Comment by Pilsner77** [comment]
Tastatur über USB Dongle ( Adabter ) anschließen und  mit Tastatur steuern  Lauter Leise ,fals nix mehr geht

**Comment by gjf** [comment]
Latest module is here: https://github.com/Magisk-Modules-Grave/gjf_bt
Although the development is stopped.
