### ISSUE TITLE
Redmi 8 pro Unstable work

### ISSUE THREAD

**Issue by kot6230** [gjf/gjf_bt#6]
Sometimes when rebooting, the phone does not initialize sim, fast charging, WiFi, and sometimes camera has to restart the phone several times. Disabled one module at a time and eventually found out that it was in your module.
![Screenshot_2020-01-31-11-34-19-816_com PUl qUGU R45Pe M](https://user-images.githubusercontent.com/60502974/73524209-b5058680-441d-11ea-9655-9a9bbc840f76.png)

**Comment by kot6230** [comment]
I from Russia used Google translate

**Comment by gjf** [comment]
It means this module cannot work with your phone.
I can blacklist it - just send me your build.prop file.

**Comment by gjf** [comment]
BTW the latest version is here: https://github.com/Magisk-Modules-Grave/gjf_bt
Although the development is stopped.
