### ISSUE TITLE
Module SBC-HD for Lineage OS 17.1

### ISSUE THREAD

**Issue by integralnik** [gjf/gjf_bt#7]
Will there be an SBC-HD module version for Lineageos 17.1?  In version 16.1 based on Android 9, this mode was introduced by the developer.  Android 10 doesn’t have this mode. Will a mod for Android 10 Lineage OS 17.1 be released?

**Comment by gjf** [comment]
1. I never supported LineageOS.

2. This module was made just for fun and just for my phone. As for now I'm using another phone so I am not interested in development of this module any more.

3. The sources of this module are open same as for any Magisk module. So anybody can continue this work by making a fork.
