### ISSUE TITLE
Android 12 / MIUI 13 support

### ISSUE THREAD

**Issue by devnoname120** [gjf/gjf_bt#8]
What's missing to make this module compatible with Android 12 / MIUI 13?
AAC's quality is mediocre on the Mi Note 10 Lite so I'd like to switch to SBC XQ, which has a more consistent implementation across Android devices.

**Comment by gjf** [comment]
Do it: the source is open. 
I stopped maintaining this module a long time ago.

**Comment by devnoname120** [comment]
@gjf I would like to do the work by myself but could you give me some pointers about what made it stop working if you remember?

**Comment by gjf** [comment]
It didn't stop working.
I simply stopped using MIUI-based devices.
No device - no test - no development.

**Comment by devnoname120** [comment]
Thanks. I thought the Android version check in the code meant it didn't work rather than is untested.

**Comment by devnoname120** [comment]
@gjf Could you tell me where the [SO files](https://github.com/gjf/gjf_bt/tree/master/system/lib) are from? If I need to update them it would make my life easier to know where to look.

**Comment by gjf** [comment]
https://habr.com/ru/post/433502/
